aiospamc/incremental_parser.py
tests/test_incremental_parser.py

Added another parser based on the requirements from #186 
It uses more built-in functions and is a lot simpler.  It ends up being at least twice as fast as the current parser too.

Incremental parser

---

aiospamc/common.py
aiospamc/header_values.py
aiospamc/requests.py
aiospamc/responses.py
tests/test_common.py
tests/test_header_values.py
tests/test_requests.py
tests/test_responses.py

Adds __str__ methods to objects to allow developers to more easily work use the REPL. #196

Nicer object strings

---

aiospamc/incremental_parser.py

Added docstrings for the incremental_parser module.

Added docstrings for the incremental_parser module

---

README.rst
example/client_object_example.py
example/gtube_example.py

Updated main example and added one demonstrating TELL with the Client class #198

Updated examples

---

aiospamc/incremental_parser.py
docs/conf.py

Fixed spelling mistakes and added configuration options for Sphinx's autodoc

Docstring fixes

---

utils/set_version.py

Added utility to set versions in all files that need to be updated.

Added script to update versions

---

aiospamc/client.py

Loop parameter is passed to the connection

Pass loop parameter to the connection

---

README.rst
example/client_object_example.py
example/gtube_example.py

* Set minimum Python version to 3.6 to match pyproject.toml
* Removed loop parameters from all examples and README

Update examples and README

---

aiospamc/incremental_parser.py
aiospamc/responses.py

Using automatic values for Enum #217

Updated enum to use auto where possible

---

aiospamc/__init__.py
aiospamc/client.py
aiospamc/connections.py
docs/user_guide.rst
tests/test_connections.py

Added feature for connection timeouts, fixing #222

Connection timeout

---

aiospamc/client.py
aiospamc/connections.py
docs/user_guide.rst
tests/conftest.py
tests/test_client.py
tests/test_connections.py
tests/test_incremental_parser.py
tests/test_requests.py

Added additional logging calls and improved the data provided through logging.

Improved logging

---

docs/index.rst
docs/user_guide.rst
pyproject.toml

Added documentation link to pyproject.toml
Fixes in documentation

Documentation fixes

---

aiospamc/responses.py

Renamed to match original class name
Changed Response contructor to declare backing property instead of
assigning it

Renamed StatusCode to Status

---

aiospamc/connections.py
aiospamc/exceptions.py
aiospamc/frontend.py
aiospamc/incremental_parser.py
aiospamc/responses.py
tests/test_connections.py
tests/test_frontend.py
tests/test_responses.py

Implemented exception chaining across the code base
Added distinction between server and client timeout exceptions

Helpful exceptions

---

README.rst

Fixed the build IDs the for the build and coverage shields, resolves #286

---

aiospamc/responses.py
changes/288.bug
tests/test_responses.py

Response objects return False when compared with other objects

---

.azure-pipelines/templates/ci_steps.yaml
aiospamc/connections.py
aiospamc/exceptions.py
aiospamc/frontend.py
aiospamc/header_values.py
aiospamc/incremental_parser.py
aiospamc/requests.py
aiospamc/responses.py
poetry.lock
pyproject.toml

Add Interrogate to CI pipeline

---

aiospamc/header_values.py
aiospamc/options.py
changes/300.feature
tests/test_header_values.py

Used dataclasses for any plain old data classes.
Removed __str__ from header value classes.
Resolves #300

Implement dataclasses

---

.azure-pipelines/ci.yaml
README.rst
docs/requirements.txt
docs/user_guide.rst
poetry.lock
pyproject.toml
tests/conftest.py

Dependencies updated to support at least Python 3.7 #302 
Updated project definition and documentation for Python 3.7 #299

Python 3.7 dependencies

---

aiospamc/__init__.py
aiospamc/client.py
aiospamc/connections.py
aiospamc/frontend.py
aiospamc/incremental_parser.py
docs/requirements.txt
docs/user_guide.rst
poetry.lock
pyproject.toml
releasenotes/notes/321-logging-to-loguru-d7e61fc248d933c2.yaml
tests/test_connections.py

- Replaced logging with loguru #321
- Removed unused variable from parser
- Fixed type hints for loguru

Switch from logging to loguru

---

aiospamc/header_values.py
aiospamc/requests.py
aiospamc/responses.py
aiospamc/user_warnings.py
tests/test_header_values.py
tests/test_integration_ssl.py
tests/test_integration_tcp.py
tests/test_requests.py
tests/test_responses.py
tests/test_warnings.py

Added to_json methods to all models
Cleaned up warnings

Convert objects to dictionaries

---

.github/workflows/codeql-analysis.yml
.github/workflows/integration-tests.yml
.github/workflows/quality.yml
.github/workflows/unit-tests.yml

Switch master branch to main

---

.github/workflows/codeql-analysis.yml
.github/workflows/integration-tests.yml
.github/workflows/quality.yml
.github/workflows/release.yml
.github/workflows/unit-tests.yml

Actions versions

---

.github/workflows/integration-tests.yml
.github/workflows/quality.yml
.github/workflows/release.yml
.github/workflows/unit-test-pre.yml
.github/workflows/unit-tests.yml

Added pipeline for testing pre-release Python versions
Added cache for dependencies

GitHub Actions Update

---

README.rst
docs/cli.rst

Fixed missing argument
Added README example

Updates to CLI documentation

---

.github/release-notes.yml

Excluding pre-commit bot from generated release notes

---

aiospamc/__init__.py
aiospamc/cli.py
pyproject.toml
releasenotes/notes/405-cli-report-doesnt-set-user-11fb68eae45c4178.yaml

- Fixed reports CLI not setting user header #405 
- Bump to 0.10.1

merge 0.10.1

---

.github/workflows/unit-test-pre.yml
.github/workflows/unit-tests.yml
poetry.lock
pyproject.toml
readthedocs.yml
releasenotes/notes/422-python-3.12-7b714da4ca0d8564.yaml

Added support for Python 3.12, closes #422

Add support for Python 3.12

---

aiospamc/connections.py
aiospamc/frontend.py
aiospamc/incremental_parser.py
aiospamc/requests.py
aiospamc/responses.py

Using standard collection type hints #464

---

tests/conftest.py

Updated datetime method to avoid deprecation warning

---

poetry.lock
pyproject.toml

Update cryptography to close OpenSSL vulnerability

---

aiospamc/__init__.py
poetry.lock
pyproject.toml

Using importlib for package version
